common:
  workQueue:
    maxQueueNum: 1000
    maxThreadNum: 100
  serverConfig:
    host: 192.168.68.25
    port: 9092
    zone: 1
    id: tcp-ws-01
    name: tcp-ws-01
  regServer:
    host: 192.168.68.25
    port: 9090
  mqProxy:
    nameSrv: 120.79.235.83:9876
    producerGroup: online-produce-1
    consumerGroup: online-consumer-1
    topic: TopicTest-1

logging:
  config: classpath:config/logback-spring.xml
  file:
    name: logs/ws-gw.log