common:
  workQueue:
    maxQueueNum: 1000
    maxThreadNum: 100
  serverConfig:
    host: 192.168.3.014
    port: 9091
    zone: 1
    id: gw-ws-01
    name: gw-ws-01
  regServer:
    host: 192.168.3.014
    port: 9090
  mqProxy:
    dialect: rocketmq
    topic: TopicTest-1
    rocketMq:
      nameSrv: 120.79.235.83:9876
      producerGroup: online-produce-1
      consumerGroup: online-consumer-1

  sysEvent:
    userTopic: UserEvent
    serviceTopic: ServiceEvent

logging:
  config: classpath:config/logback.xml
  file:
    name: logs/ws-gw.log