common:
  workQueue:
    maxQueueNum: 1000
    maxThreadNum: 100
  serverConfig:
    host: 192.168.68.25
    port: 9091
  regServer:
    host: 192.168.68.25
    port: 9090
    topic: topic-reg-server

logging:
  config: classpath:config/logback-spring.xml
  file:
    name: logs/ws-gw.log