common:
  workQueue:
    maxQueueNum: 1000
    maxThreadNum: 100
  serverConfig:
    host: 192.168.1.102
    port: 9090

logging:
  config: classpath:configuration/logback-spring.xml
  file:
    name: logs/registration.log