common:
  serverConfig:
    zone: 1
    id: gw-online-01
    name: gw-online-01
  mqProxy:
    nameSrv: 120.79.235.83:9876
    producerGroup: online-produce-3
    consumerGroup: online-consumer-2
    topic: TopicTest
  regServer:
    host: 192.168.3.104
    port: 9090
  sysEvent:
    userTopic: UserEvent
    serviceTopic: ServiceEvent

logging:
  config: classpath:config/logback-spring.xml
  file:
    name: logs/ws-online.log